# Use root/example as user/password credentials
version: '3.8'

services:
  dynamodb:
    container_name: cxcxc-db
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
networks:
  default:
    name: cxcxc-sam